# Generated by Django 2.2.1 on 2019-08-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='name',
            new_name='full_name',
        ),
    ]
