# Generated by Django 2.2.1 on 2019-08-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_message',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
