# Generated by Django 2.2.1 on 2019-08-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_author_author_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=200)),
            ],
        ),
    ]
