# Generated by Django 2.2.1 on 2019-08-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_lol_champs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lol_champs',
            old_name='champ_name',
            new_name='name',
        ),
    ]
