# Generated by Django 2.2.1 on 2019-08-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20190821_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.FloatField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
