# Generated by Django 2.2.1 on 2019-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_phonebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
