# Generated by Django 2.2.1 on 2019-11-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='incomplete',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
