# Generated by Django 2.2.1 on 2019-11-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_task_incomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='incomplete',
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
