# Generated by Django 2.2.1 on 2020-03-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_award_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
