# Generated by Django 2.2.1 on 2020-03-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_nbateam_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.CharField(max_length=255),
        ),
    ]
