# Generated by Django 2.2.1 on 2020-03-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_auto_20200311_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.IntegerField(),
        ),
    ]
