# Generated by Django 2.2.1 on 2020-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_auto_20200311_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.IntegerField(null=True),
        ),
    ]
