# Generated by Django 2.2.1 on 2020-03-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_auto_20200318_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
    ]
