# Generated by Django 2.2.1 on 2020-03-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_nbateam_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
