# Generated by Django 2.2.1 on 2020-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_auto_20200323_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='ticket_sales',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
