# Generated by Django 2.2.1 on 2020-03-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0029_nbateam_ticket_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
        migrations.RemoveField(
            model_name='nbateam',
            name='ticket_sales',
        ),
    ]
