# Generated by Django 2.2.1 on 2020-03-24 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0030_auto_20200323_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.ForeignKey(default=189, on_delete=django.db.models.deletion.CASCADE, to='exercises.City'),
            preserve_default=False,
        ),
    ]
