# Generated by Django 3.1.5 on 2021-01-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0031_nbateam_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
    ]
