# Generated by Django 3.1.5 on 2021-01-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0032_remove_nbateam_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='museum',
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog_Data',
        ),
        migrations.DeleteModel(
            name='Credit_Card',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Food_List',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Lol_Champs',
        ),
        migrations.DeleteModel(
            name='Marvel_List',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Phonebook',
        ),
        migrations.DeleteModel(
            name='Phonebook2',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='award',
        ),
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Art',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Museum',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Winners',
        ),
    ]
